### ISSUE TITLE
Exclamation mark in heading triggers two text events

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [google/pulldown-cmark#108]
When the parser is parsing a markdown file with for example the heading `# Heading!` it will send two text events. One for the text up to the exclamation mark and one for the exclamation mark.

I think this is a bug. Possibly related to the exclamation mark being used as part of non heading syntax in Markdown.

**Comment by raphlinus** [comment]
This is expected behavior. The `!` is possibly the beginning of an image, so it triggers inline markup detection, which in turn closes the text event. Note that cmark has similar behavior.

It's possible to fuse text events together as a wrapper around the existing iterator, but this would be a bit of extra overhead and not helpful if the text event is simple (ie just outputting escaped HTML). I'd be open to a PR that adds such an iterator, and possibly as an option to the parser (assuming it doesn't impact performance in the main case).

**Comment by ZelphirKaltstahl** [comment]
@raphlinus Expected behavior to expect an image in a heading? Seems weird. Never seen an image in a heading in Markdown and I think that is not even part of any specification. Why would that be expected behavior? I think the parser should recognize that it is inside a heading and then depending on that fact not try to do image stuff. Context-aware.

Anyway I also already tried with `\!` to no avail, still two text events. `\` is defined as "escaping" so at least in that case it should only generate one text event.

**Comment by ScottAbbey** [comment]
Since pulldown-cmark is intended to match CommonMark, if in doubt, check the CommonMark dingus:

http://spec.commonmark.org/dingus/?text=%23%20Heading!

It looks like they generate two text items as well (view the AST tab). So if you still think it is a bug, you can take it up over at commonmark/CommonMark on github.

**Comment by ZelphirKaltstahl** [comment]
I think you are right according to specification and example implementation. I could not imagine that they would have it behaving that way too!

It is quite weird, that they did not catch that case. To me it makes no sense to see an exclamation mark in some text element as something different than just another text character. I do not see the reasoning behind making it two text elements.

My reasoning would be, that a heading is text too, in general, in almost all kinds of documents and so all kinds of normal text characters should be expected.

Fun fact: A question mark will not result in an extra element on the spec page that was linked above. Neither will another `#` at the end not separated by a space, nor will `(` or `)`. But `[` and `]` will result in extra elements. Also any escaping on those characters does not change the behavior. Basically escaping is useless in headings.

Maybe CommonMark is not yet that far in standardizing things.
